//  FICHERO AUTOGENERADO - NO MODIFICAR
//  StoryboardConstants.h
//
//  Created by SDOS
//

#import <Foundation/Foundation.h>

extern NSString * const SBNameExampleKZBootstrap;

 //
 // ExampleKZBootstrap.h
 // Generated by seguecode

#pragma once

#import <UIKit/UIKit.h>

@interface UINavigationController (ExampleKZBootstrap)

@end
#import "DocumentationKZBootstrapViewController.h"

@interface DocumentationKZBootstrapViewController (ExampleKZBootstrap)

@end
#import "ExampleKZBootstrapViewController.h"

@interface ExampleKZBootstrapViewController (ExampleKZBootstrap)

@end

// Auto generated file - any changes will be lost

#import <Foundation/Foundation.h>

#pragma mark - navigationController.storyboardIdentifier
extern NSString * const ExampleKZBootstrapNavigationController;

#pragma mark - storyboardNames
extern NSString * const ExampleKZBootstrap;


