//  FICHERO AUTOGENERADO - NO MODIFICAR
//  StoryboardConstants.m
//
//  Created by SDOS
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

NSString * const SBNameExampleKZBootstrap = @"ExampleKZBootstrap";

 //
 // ExampleKZBootstrap.m
 // Generated by seguecode


@implementation UINavigationController (ExampleKZBootstrap)

@end
@implementation DocumentationKZBootstrapViewController (ExampleKZBootstrap)

@end
@implementation ExampleKZBootstrapViewController (ExampleKZBootstrap)

@end

// Auto generated file - any changes will be lost


#pragma mark - navigationController.storyboardIdentifier
NSString * const ExampleKZBootstrapNavigationController = @"ExampleKZBootstrapNavigationController";

#pragma mark - storyboardNames
NSString * const ExampleKZBootstrap = @"ExampleKZBootstrap";


